-- 없어진 기록 찾기 (보호실을 온 기록이 없는 동물 조회)
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_INS AS INS 
    RIGHT JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID 
WHERE INS.ANIMAL_ID IS NULL -- 보호실을 온 기록이 없는 동물들
ORDER BY OUTS.ANIMAL_ID

-- 있었는데 없었습니다. (보호일 보다 입양일이 더빠른 동물 조회)
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS AS INS 
    LEFT JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID 
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME

-- 오랜기간 보호한 동물(1)
SELECT INS.NAME, INS.DATETIME
FROM ANIMAL_INS AS INS 
    LEFT JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID 
WHERE OUTS.DATETIME IS NULL
ORDER BY INS.DATETIME
LIMIT 3

-- 보호소에서 중성화한 동물
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS AS i 
    LEFT JOIN ANIMAL_OUTS AS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE (i.SEX_UPON_INTAKE LIKE "%Intact%") AND (o.SEX_UPON_OUTCOME NOT LIKE "%Intact%")